/* BUSCO! V5 · medición opcional + consentimiento + legal · 08/10/2026 */
(()=>{'use strict';
const cfg=window.BUSCO_CONFIG||{};
const types=new Set(['page_view','search','tool_detail','compare_add','compare_remove','compare_open','compare_complete','affiliate_click','official_click','whatsapp_click','portfolio_open','guide_open','guide_apply','voice_play','implementation_request','partner_request_open','partner_request_submit','rating_submit']);
const read=(s,k)=>{try{return s.getItem(k);}catch{return null;}},write=(s,k,v)=>{try{s.setItem(k,v);}catch{}},remove=(s,k)=>{try{s.removeItem(k);}catch{}};
const CONSENT_KEY='busco_consent',CONSENT_VERSION='2026-10-08-v2',MAX_AGE=1000*60*60*24*730;
const disabled=()=>navigator.globalPrivacyControl===true;
function lang(){const l=(window.BUSCO_CURRENT_LANG||document.documentElement.lang||'es').toLowerCase();return l.startsWith('en')?'en':l.startsWith('ca')?'ca':'es';}
const copy={
 es:{title:'Cookies',text:'Usamos almacenamiento necesario para recordar tu idioma y tus preferencias. Si aceptas, también mediremos de forma agregada qué páginas, herramientas y botones se usan para mejorar BUSCO!. No guardamos el texto de tus búsquedas. Puedes aceptar o rechazar y seguir usando la web.',accept:'Aceptar',reject:'Rechazar',manage:'Cookies',privacy:'Política de privacidad',cookies:'Política de cookies',legal:'Aviso legal',affiliate:'Afiliación y transparencia',note:'Puedes cambiar esta elección cuando quieras desde “Cookies”.',gpc:'Tu navegador ha activado una señal de privacidad global, por lo que la medición opcional permanece desactivada.',affNote:'Algunos enlaces son de afiliación: BUSCO! puede recibir una comisión si contratas, sin coste adicional para ti. Esto no altera el orden del buscador ni el encaje de los resultados.',legalLabel:'Legal y privacidad',cookieManage:'Configurar cookies'},
 en:{title:'Cookies',text:'We use necessary storage to remember your language and preferences. If you accept, we will also measure in aggregate which pages, tools and buttons are used to improve BUSCO!. We do not store the text of your searches. You can accept or reject and keep using the website.',accept:'Accept',reject:'Reject',manage:'Cookies',privacy:'Privacy policy',cookies:'Cookie policy',legal:'Legal notice',affiliate:'Affiliate transparency',note:'You can change this choice at any time from “Cookies”.',gpc:'Your browser has enabled Global Privacy Control, so optional measurement remains disabled.',affNote:'Some links are affiliate links: BUSCO! may receive a commission if you purchase, at no extra cost to you. This does not alter search order or result fit.',legalLabel:'Legal & privacy',cookieManage:'Cookie settings'},
 ca:{title:'Cookies i mesurament',text:'BUSCO! utilitza emmagatzematge tècnic per recordar l’idioma i les preferències. Si acceptes el mesurament, també podrem saber de manera agregada quines pàgines, eines i botons s’utilitzen. No guardem el text de les teves cerques a l’analítica.',accept:'Acceptar mesurament',reject:'Només necessàries',manage:'Cookies',privacy:'Política de privacitat',cookies:'Política de cookies',legal:'Avís legal',affiliate:'Afiliació i transparència',note:'Pots canviar aquesta elecció quan vulguis des de “Cookies”.',gpc:'El navegador ha activat el Control Global de Privacitat, de manera que el mesurament opcional continua desactivat.',affNote:'Alguns enllaços són d’afiliació: BUSCO! pot rebre una comissió si contractes, sense cap cost addicional per a tu. Això no altera l’ordre del cercador ni l’encaix dels resultats.',legalLabel:'Legal i privacitat',cookieManage:'Configurar cookies'}
};
function paths(l=lang()){if(l==='en')return {privacy:'/en/legal/privacy/',cookies:'/en/legal/cookies/',legal:'/en/legal/legal-notice/',affiliate:'/en/legal/affiliate-transparency/'};if(l==='ca')return {privacy:'/ca/legal/privacitat/',cookies:'/ca/legal/cookies/',legal:'/ca/legal/avis-legal/',affiliate:'/ca/legal/afiliacio-transparencia/'};return {privacy:'/legal/privacidad/',cookies:'/legal/cookies/',legal:'/legal/aviso-legal/',affiliate:'/legal/afiliacion/'};}
function readConsent(){const raw=read(localStorage,CONSENT_KEY);if(!raw)return null;try{const o=JSON.parse(raw);if(!o||o.version!==CONSENT_VERSION||!['accepted','rejected'].includes(o.status)||Date.now()-Number(o.at||0)>MAX_AGE)return null;return o;}catch{return null;}}
let current=readConsent(),consent=current?.status==='accepted'&&!disabled(),vid,sid,first,last,lastAt=0,inflight=new Set();
function initIds(){if(vid)return;vid=read(localStorage,'busco_vid')||crypto.randomUUID();sid=read(sessionStorage,'busco_sid')||crypto.randomUUID();write(localStorage,'busco_vid',vid);write(sessionStorage,'busco_sid',sid);const p=new URLSearchParams(location.search);let ref='direct';try{ref=document.referrer?new URL(document.referrer).hostname:'direct';}catch{};last={source:(p.get('utm_source')||ref).slice(0,100),medium:(p.get('utm_medium')||'').slice(0,100),campaign:(p.get('utm_campaign')||'').slice(0,100)};try{first=JSON.parse(read(localStorage,'busco_first_touch'))||last;}catch{first=last;}write(localStorage,'busco_first_touch',JSON.stringify(first));write(localStorage,'busco_last_touch',JSON.stringify(last));}
async function track(type,extra={}){if(!consent||disabled()||!types.has(type)||!cfg.supabaseUrl||!cfg.publishableKey)return null;if(Date.now()-lastAt<80&&type==='search')return null;lastAt=Date.now();initIds();const id=crypto.randomUUID(),row={id,event_type:type,visitor_id:vid,session_id:sid,tool_slug:extra.tool_slug||extra.tool_id||null,page_path:location.pathname,utm_source:last.source,utm_medium:last.medium,utm_campaign:last.campaign,first_source:first,last_source:last,query_length:String(extra.query||'').length,selected_count:Number(extra.selected_count||0),surface:String(extra.surface||'').slice(0,80),action:String(extra.action||'').slice(0,80)};const controller=new AbortController();inflight.add(controller);try{const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+'/rest/v1/rpc/collect_event',{method:'POST',keepalive:true,signal:controller.signal,headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({event:row})});if(!r.ok||await r.json()!==true)return null;return id;}catch{return null;}finally{inflight.delete(controller);}}
window.BUSCO_TRACK=track;
function clearAnalytics(){for(const c of inflight)c.abort();for(const k of ['busco_vid','busco_first_touch','busco_last_touch','busco_public_analytics_v1'])remove(localStorage,k);remove(sessionStorage,'busco_sid');vid=sid=first=last=null;}
function closePanel(){document.getElementById('buscoConsent')?.remove();}
function setConsent(accepted){consent=Boolean(accepted)&&!disabled();write(localStorage,CONSENT_KEY,JSON.stringify({status:consent?'accepted':'rejected',at:Date.now(),version:CONSENT_VERSION}));current=readConsent();if(!consent)clearAnalytics();else track('page_view');closePanel();}
window.BUSCO_SET_CONSENT=setConsent;
window.BUSCO_GET_ANON_VISITOR=()=>{if(!consent||disabled())return null;initIds();return vid;};
window.BUSCO_OPEN_COOKIE_SETTINGS=()=>panel(false);

window.BUSCO_RATE_TOOL=async function(toolSlug,rating){
 if(!consent||disabled()){panel(false);throw new Error('Para guardar una valoración anónima hay que aceptar la medición opcional.');}
 initIds();const value=Number(rating);if(!Number.isInteger(value)||value<1||value>5)throw new Error('La valoración debe estar entre 1 y 5.');
 const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+'/rest/v1/rpc/submit_tool_rating',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({p_tool_slug:toolSlug,p_visitor_id:vid,p_rating:value})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||'No se pudo guardar la valoración.');const out=await r.json();track('rating_submit',{tool_slug:toolSlug,action:String(value),surface:'ficha'});return out;
};
window.BUSCO_SUBMIT_TOOL_REQUEST=async function(payload){if(!cfg.supabaseUrl||!cfg.publishableKey)throw new Error('BUSCO no está conectado.');const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+'/rest/v1/rpc/submit_tool_request',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({request:payload})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||'No se pudo registrar la solicitud.');const out=await r.json();track('partner_request_submit',{surface:'partner_form'});return out;};
function injectStyles(){if(document.getElementById('buscoLegalRuntimeStyle'))return;const s=document.createElement('style');s.id='buscoLegalRuntimeStyle';s.textContent=`
#buscoConsent{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:20px;background:rgba(0,3,8,.78);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);font-family:Inter,"Segoe UI",Arial,sans-serif}
#buscoConsent .bc-consent-card{width:min(620px,100%);padding:22px;border:1px solid rgba(89,226,255,.48);border-radius:20px;background:linear-gradient(155deg,rgba(7,16,28,.99),rgba(2,8,16,.99));color:#f7fbff;box-shadow:0 25px 90px rgba(0,0,0,.68),0 0 20px rgba(24,223,255,.09),0 0 16px rgba(255,47,183,.06)}
#buscoConsent h2{margin:0 0 8px;font-size:21px;letter-spacing:-.02em}#buscoConsent p{margin:0;color:#b9c6d6;font-size:13px;line-height:1.58}#buscoConsent .bc-consent-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:17px}#buscoConsent button{min-height:42px;border-radius:999px;padding:0 16px;font-weight:800;font-size:12px;color:#fff;background:rgba(3,10,18,.70);border:1px solid rgba(89,226,255,.55);cursor:pointer}#buscoConsent button[data-choice="reject"]{border-color:rgba(255,91,199,.55)}#buscoConsent button:hover{filter:brightness(1.12)}#buscoConsent .bc-consent-links{display:flex;gap:11px;flex-wrap:wrap;margin-top:14px}#buscoConsent .bc-consent-links a{font-size:11px;color:#8feeff;text-decoration:none}#buscoConsent .bc-consent-note{margin-top:9px;font-size:10.5px;color:#7f92a8}
#buscoCookieButton{position:fixed;left:10px;bottom:9px;z-index:99997;border:1px solid rgba(89,226,255,.30);border-radius:999px;padding:7px 11px;background:rgba(4,12,22,.80);backdrop-filter:blur(12px);color:#dce9f5;font:700 10.5px Inter,"Segoe UI",Arial,sans-serif;cursor:pointer;box-shadow:0 0 10px rgba(24,223,255,.06)}#buscoCookieButton:hover{border-color:rgba(255,91,199,.42);color:#fff}
#buscoLegalStrip{border-top:1px solid rgba(137,242,255,.10);padding:13px 18px 22px;text-align:center;background:#02050a;color:#7f92a8;font:11px/1.55 Inter,"Segoe UI",Arial,sans-serif}#buscoLegalStrip a,#buscoLegalStrip button{color:#a9bacb;background:none;border:0;padding:3px 6px;font:inherit;cursor:pointer;text-decoration:none}#buscoLegalStrip a:hover,#buscoLegalStrip button:hover{color:#fff}
#buscoAffiliateDisclosure{margin:11px 0 0;color:#788ca2;font-size:10px;line-height:1.55}#buscoAffiliateDisclosure a{color:#8ceeff;text-decoration:none}
.busco-inline-privacy{color:#7f92a8;font-size:10px;line-height:1.5}.busco-inline-privacy a{color:#8ceeff;text-decoration:underline;text-underline-offset:2px}
@media(max-width:620px){#buscoConsent{padding:12px}#buscoConsent .bc-consent-card{padding:18px}#buscoConsent .bc-consent-actions{grid-template-columns:1fr}#buscoConsent button{width:100%}#buscoCookieButton{left:8px;bottom:7px}}
`;document.head.appendChild(s);}
function panel(firstTime=true){injectStyles();closePanel();const l=lang(),c=copy[l],p=paths(l);const box=document.createElement('aside');box.id='buscoConsent';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label',c.title);box.innerHTML=`<div class="bc-consent-card"><h2>${c.title}</h2><p>${disabled()?c.gpc:c.text}</p><div class="bc-consent-actions"><button type="button" data-choice="accept">${c.accept}</button><button type="button" data-choice="reject">${c.reject}</button></div><div class="bc-consent-links"><a href="${p.cookies}">${c.cookies}</a><a href="${p.privacy}">${c.privacy}</a><a href="${p.legal}">${c.legal}</a></div><p class="bc-consent-note">${c.note}</p></div>`;box.querySelector('[data-choice="accept"]').disabled=disabled();box.querySelector('[data-choice="accept"]').onclick=()=>setConsent(true);box.querySelector('[data-choice="reject"]').onclick=()=>setConsent(false);document.body.appendChild(box);}
function ensureCookieButton(){injectStyles();let b=document.getElementById('buscoCookieButton');if(!b){b=document.createElement('button');b.id='buscoCookieButton';b.type='button';b.onclick=()=>panel(false);document.body.appendChild(b);}b.textContent=copy[lang()].manage;b.setAttribute('aria-label',copy[lang()].cookieManage);}
function ensureLegalStrip(){injectStyles();let x=document.getElementById('buscoLegalStrip');if(!x){x=document.createElement('div');x.id='buscoLegalStrip';document.body.appendChild(x);}const l=lang(),c=copy[l],p=paths(l);x.innerHTML=`<span>${c.legalLabel}:</span> <a href="${p.legal}">${c.legal}</a> · <a href="${p.privacy}">${c.privacy}</a> · <a href="${p.cookies}">${c.cookies}</a> · <a href="${p.affiliate}">${c.affiliate}</a> · <button type="button" data-cookie-settings>${c.cookieManage}</button>`;x.querySelector('[data-cookie-settings]').onclick=()=>panel(false);}
function ensureAffiliateDisclosure(){if(location.pathname!=='/'&&location.pathname!=='/index.html')return;const head=document.querySelector('#comparador .bc-head');if(!head)return;let n=document.getElementById('buscoAffiliateDisclosure');if(!n){n=document.createElement('p');n.id='buscoAffiliateDisclosure';head.insertAdjacentElement('afterend',n);}const l=lang(),p=paths(l);n.innerHTML=`${copy[l].affNote} <a href="${p.affiliate}">${copy[l].affiliate} →</a>`;}
function refreshLegalUi(){ensureCookieButton();ensureLegalStrip();ensureAffiliateDisclosure();}
function start(){remove(localStorage,'busco_public_analytics_v1');injectStyles();refreshLegalUi();if(disabled()){consent=false;clearAnalytics();if(!current)write(localStorage,CONSENT_KEY,JSON.stringify({status:'rejected',at:Date.now(),version:CONSENT_VERSION}));}else if(!current)panel(true);else if(consent)track('page_view');const mo=new MutationObserver(ms=>{if(ms.some(m=>m.type==='attributes'&&m.attributeName==='lang'))refreshLegalUi();});mo.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});}
document.addEventListener('click',e=>{const el=e.target.closest('a,button');if(!el)return;if(el.dataset.buscoAffiliate)track('affiliate_click',{tool_slug:el.dataset.buscoAffiliate,surface:el.dataset.buscoSurface||'ficha'});else if(el.dataset.buscoTrack==='portfolio'||/portfolio/i.test(el.getAttribute('onclick')||''))track('portfolio_open');else if(el.dataset.buscoTrack==='whatsapp'||/^https:\/\/(wa.me|api.whatsapp.com)\//.test(el.href||''))track('whatsapp_click',{surface:el.dataset.buscoSurface||''});},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
