(()=>{'use strict';const cfg=window.BUSCO_CONFIG||{};
const strings='what subcategory needs audience functions aiText integrations platform languages price freeText trialText advantages limitations competitors differentiator keywords primary primaryLabel ease priority verdict review masterUse searchText'.split(' ');
function url(value){if(!value)return '';const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('URL inválida');return u.href;}
function adapt(t){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(t.tracking_slug)||!t.name)throw Error('Ficha sin identidad estable');const d=t.public_data||{},r={id:t.tracking_slug,internalId:t.id,name:String(t.name),url:url(t.official_url),affiliateUrl:url(t.affiliate_url),categories:[],tags:[]};for(const k of strings)r[k]=typeof d[k]==='string'?d[k]:'';for(const k of ['categories','tags'])r[k]=Array.isArray(d[k])?d[k].filter(v=>typeof v==='string'):[];for(const k of ['hasAI','hasFree','hasSpanish','hasTrial'])r[k]=d[k]===true;r.priceMonthlyEUR=typeof d.priceMonthlyEUR==='number'&&d.priceMonthlyEUR>=0?d.priceMonthlyEUR:null;r.what=t.description||r.what;r.primary=r.primary||t.category||'';r.primaryLabel=r.primaryLabel||t.category||'';if(!r.categories.length&&r.primary)r.categories=[r.primary];r.commercialStatus=r.affiliateUrl?'Afiliado':'Sin acuerdo';r.catalogStatus='Esencial';r.searchText=[r.name,...strings.map(k=>r[k]),...r.tags].join(' ');return r;}
function affiliateLinks(){for(const a of document.querySelectorAll('.bc-web-link:not([data-seo-link]),[data-official-tool]')){const id=a.dataset.officialTool||a.closest('[data-tool]')?.dataset.tool;const t=window.BUSCO_CATALOG?.find(x=>x.id===id);if(!t?.affiliateUrl||!['Afiliado','Destacado'].includes(t.commercialStatus||t.commercial_status||'Sin acuerdo')||a.dataset.buscoAffiliate)continue;a.href=t.affiliateUrl;a.rel='sponsored noopener noreferrer';a.dataset.buscoAffiliate=t.id;a.textContent='VISITAR '+t.name+' ↗';}}
async function start(){if(cfg.catalogMode==='remote'){try{if(!cfg.supabaseUrl||!cfg.publishableKey)throw Error('Falta configuración');const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+'/rest/v1/rpc/published_catalog',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error('Catálogo no disponible');const raw=await r.json();if(!Array.isArray(raw)||!raw.length)throw Error('Catálogo vacío');const list=raw.map(adapt);if(new Set(list.map(x=>x.id)).size!==list.length)throw Error('Slugs repetidos');window.BUSCO_REPLACE_CATALOG(list);window.BUSCO_CATALOG_SOURCE='remote';}catch(e){window.BUSCO_CATALOG_SOURCE='embedded-fallback';console.warn('BUSCO conserva el catálogo incluido:',e.message);}}
const obs=new MutationObserver(()=>affiliateLinks());for(const id of ['bcResults','bcDetail']){const el=document.getElementById(id);if(el)obs.observe(el,{childList:true});}affiliateLinks();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,0));else setTimeout(start,0);
})();
