'use strict';
const cfg=window.BUSCO_CONFIG||{},Core=window.BuscoCore;
const tables={tools:'tools',events:'events',clients:'clients',client_documents:'client_documents',money:'commissions',billing:'billing',issues:'issues',projects:'projects',payments:'payments',leads:'leads',audit_log:'audit_log'};
let connected=false,refreshTimer,importPlan=null,searchTimer;
function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function fail(e){alert(e.message||String(e));}
window.addEventListener('unhandledrejection',e=>{e.preventDefault();fail(e.reason);});
function requireAccess(){if(!connected&&!cfg.allowLocal)throw Error('Inicia sesión para trabajar con datos compartidos.');}
function validateConfig(url,key){if(!/^https:\/\/[^/]+$/.test(url))throw Error('Usa la URL HTTPS de tu proyecto Supabase');if(!key||key.startsWith('sb_secret_'))throw Error('Usa únicamente una clave publicable');if(key.startsWith('eyJ')){try{if(JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role!=='anon')throw Error();}catch{throw Error('La clave JWT debe ser anon; nunca service_role');}}}
async function api(path,options={}){requireAccess();const r=await fetch(remote.url+path,{...options,headers:{...rh(),...options.headers}});if(!r.ok){if(r.status===401){connected=false;clearInterval(refreshTimer);showGate();throw Error('La sesión ha caducado. Vuelve a entrar; no se ha guardado el cambio.');}let body=await r.json().catch(()=>({}));throw Error(body.message||body.msg||'No se pudo guardar/cargar ('+r.status+').');}if(r.status===204)return null;return r.json();}
async function rpc(name,args){return api('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(args)});}
login=async function(){remote.url=($('#sbUrl').value||cfg.supabaseUrl||'').trim().replace(/\/$/,'');remote.key=($('#sbKey').value||cfg.publishableKey||'').trim();validateConfig(remote.url,remote.key);const email=$('#sbEmail').value.trim(),password=$('#sbPass').value;if(!email||!password)throw Error('Indica correo y contraseña');const r=await fetch(remote.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:remote.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});$('#sbPass').value='';if(!r.ok)throw Error('No se pudo iniciar sesión. Comprueba tus datos.');const session=await r.json();remote.token=session.access_token;remote.email=email;connected=true;try{if(!await rpc('is_internal',{}))throw Error('Este usuario no está autorizado para BUSCO Control');await loadRemote();}catch(e){connected=false;remote.token='';throw e;}$('#mode').textContent='Compartido · '+email;$('#loginInfo').textContent='Conectada';$('#authGate')?.remove();document.body.classList.remove('locked');localStorage.setItem('busco_sb_url',remote.url);localStorage.setItem('busco_sb_key',remote.key);clearInterval(refreshTimer);refreshTimer=setInterval(async()=>{try{const r=await fetch(remote.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:remote.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)throw Error();Object.assign(session,await r.json());remote.token=session.access_token;}catch{connected=false;remote.token='';clearInterval(refreshTimer);showGate();}},Math.max(30000,(session.expires_in-120)*1000));};
async function logout(){if(connected)await fetch(remote.url+'/auth/v1/logout',{method:'POST',headers:rh()}).catch(()=>{});connected=false;remote.token='';clearInterval(refreshTimer);sessionStorage.removeItem('busco_token');sessionStorage.removeItem('busco_email');for(const k of Object.keys(tables))db[k]=[];render();showGate();}
function showGate(){document.body.classList.add('locked');$('.nav[data-v="settings"]').click();if($('#authGate'))return;const n=document.createElement('div');n.id='authGate';n.className='note';n.textContent='BUSCO Control privado. Inicia sesión con tu cuenta de Clara o Esther. Los datos compartidos no se guardan en este navegador.';$('#v-settings').prepend(n);$('#mode').textContent='Sin sesión';}
async function allRows(table){let rows=[],offset=0;for(;;){const page=await api(`/rest/v1/${table}?select=*&order=${table==='audit_log'?'id.desc':'id.asc'}&limit=500&offset=${offset}`);rows.push(...page);if(page.length<500)break;offset+=500;if(offset>=200000)throw Error('Demasiados registros para esta vista. Requiere paginación de servidor antes de continuar.');}return rows;}
loadRemote=async function(){const entries=await Promise.all(Object.entries(tables).map(async([k,t])=>[k,await allRows(t)]));const next=Object.fromEntries(entries);next.money=next.money.map(fromCommission);next.issues=next.issues.map(x=>({...x,tool:x.tool_name}));db=next;render();renderExtras();};
function fromCommission(x){return {...x,tool:x.tool_name,sale:x.sale_amount,expected:x.expected_commission,reported:x.reported_commission,partner_id:x.partner_transaction_id};}
function toRow(t,row){const r={...row};if(t==='money'){Object.assign(r,{tool_name:r.tool,sale_amount:r.sale,expected_commission:r.expected,reported_commission:r.reported,partner_transaction_id:r.partner_id});for(const k of ['tool','sale','expected','reported','partner_id'])delete r[k];}if(t==='issues'){r.tool_name=r.tool??r.tool_name;delete r.tool;}for(const k of ['date','invoice_date','review_date','paid_date','due_date','cookie_days','tool_id','project_id','commission_id'])if(r[k]==='')r[k]=null;delete r.created_at;delete r.updated_at;return r;}
function validate(t,r){if(!Core.uuidRE.test(r.id))throw Error('Identificador inválido');for(const k of ['official_url','affiliate_url'])if(r[k])Core.safeURL(r[k]);for(const k of ['sale','expected','reported','paid_commission','budget_total','paid_amount','invoice_total','amount','total'])if(r[k]!=null&&(!Number.isFinite(Number(r[k]))||Number(r[k])<0))throw Error('Importe inválido: '+k);if(t==='tools'&&!String(r.name||'').trim())throw Error('Falta el nombre');if(t==='money'&&r.status==='Pagada'&&(r.paid_commission==null||!r.paid_date))throw Error('Indica importe y fecha de cobro');}
upsert=async function(t,row){requireAccess();const old=db[t].find(x=>x.id===row.id);row={...old,...row};validate(t,row);if(!connected){const n=db[t].findIndex(x=>x.id===row.id);row.updated_at=new Date().toISOString();if(n<0)db[t].push(row);else db[t][n]=row;save();return row;}const result=await rpc('save_record',{table_key:tables[t],payload:toRow(t,row),expected:old?.updated_at||null});await loadRemote();return result;};
const oldSave=save;save=function(){if(connected)throw Error('No se permite guardar datos compartidos en local');if(!cfg.allowLocal)throw Error('Modo local desactivado');oldSave();renderExtras();};
del=async function(t,id){requireAccess();if(t==='billing'&&db.billing.find(x=>x.id===id)?.source_id)throw Error('Edita o elimina el registro de origen para corregir este movimiento');if(!confirm('¿Eliminar este registro? La base de datos conservará el historial.'))return;if(connected){await api(`/rest/v1/${tables[t]}?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=representation'}});await loadRemote();}else{db[t]=db[t].filter(x=>x.id!==id);save();}};
const legacyClientSync=syncBillingFromClient,legacyCommissionSync=syncBillingFromCommission;
syncBillingFromClient=async c=>{if(!connected)await legacyClientSync(c);};
syncBillingFromCommission=async c=>{if(!connected){let b=db.billing.find(x=>x.source_id===c.id&&x.source_type==='Afiliación');await upsert('billing',{id:b?.id||uid(),source_id:c.id,source_type:'Afiliación',date:c.paid_date||c.date,party:c.tool,total:c.reported??c.expected??0,paid_amount:c.paid_commission??0,status:c.status});}};
importCatalogFile=async function(file){if(!file)return;requireAccess();if(file.size>10*1024*1024)throw Error('Máximo 10 MB por importación');let rows;if(/\.xlsx$/i.test(file.name))rows=await Core.xlsx(file);else if(/\.json$/i.test(file.name)){let obj=JSON.parse(await file.text());rows=Array.isArray(obj)?obj:obj.tools;}else rows=Core.csv(await file.text());importPlan=Core.plan(rows,db.tools,uid);openM('Revisar importación',`<div class="note">${importPlan.changes.filter(x=>x.action==='create').length} nuevas · ${importPlan.changes.filter(x=>x.action==='update').length} actualizadas · ${importPlan.errors.length} errores. No se guardará nada mientras haya errores.</div><div class="table"><table><thead><tr><th>Acción</th><th>Herramienta</th><th>Cambios</th></tr></thead><tbody>${importPlan.changes.map(x=>`<tr><td>${x.action==='create'?'Crear':'Actualizar'}</td><td>${esc(x.row.name)}</td><td>${esc(Object.keys(x.row).filter(k=>JSON.stringify(x.row[k])!==JSON.stringify(x.before?.[k])).join(', '))}</td></tr>`).join('')}</tbody></table></div><pre>${esc(importPlan.errors.map(x=>`Fila ${x.row}: ${x.error}`).join('\n'))}</pre><button class="btn" onclick="downloadImportReport()">Descargar informe</button><button class="btn" ${importPlan.errors.length?'disabled':''} onclick="commitImport(this)">Confirmar importación</button>`);};
function downloadImportReport(){download('BUSCO_informe_importacion.json',JSON.stringify(importPlan,null,2));}
async function commitImport(button){if(!importPlan||importPlan.errors.length)return;button.disabled=true;try{if(connected){await rpc('import_tools',{changes:importPlan.changes.map(c=>({row:toRow('tools',c.row),expected:c.expected}))});await loadRemote();}else{localStorage.setItem(K+'_before_import',JSON.stringify(db));for(const c of importPlan.changes){const n=db.tools.findIndex(x=>x.id===c.row.id);if(n<0)db.tools.push(c.row);else db.tools[n]=c.row;}save();}importPlan=null;closeM();}finally{button.disabled=false;}}
exportCatalogJSON=function(){download('BUSCO_catalogo_publicado.json',JSON.stringify(db.tools.filter(t=>t.public_status==='Publicado').map(t=>({id:t.id,tracking_slug:t.tracking_slug,name:t.name,category:t.category,description:t.description,official_url:t.official_url,affiliate_url:t.status==='Activa'?t.affiliate_url:null,public_data:t.public_data||{}})),null,2));};
exportCSV=function(){requireAccess();download('BUSCO_copia_datos.json',JSON.stringify(db,null,2));};
exportQuarterCSV=function(){download('BUSCO_gestoria.csv',Core.csvExport(filteredBilling().map(x=>({fecha:x.date,origen:x.source_type,cliente_herramienta:x.party,concepto:x.concept,documento:x.document_no,base:x.base_amount,iva_pct:x.vat_percent,iva_importe:x.vat_amount,total:x.total,cobrado:x.paid_amount,estado:x.status}))), 'text/csv;charset=utf-8');};
const originalFilteredBilling=filteredBilling;filteredBilling=function(){return originalFilteredBilling().filter(x=>(!$('#billingMonth').value||Number(String(x.date).slice(5,7))===Number($('#billingMonth').value))&&(!$('#billingType').value||($('#billingType').value==='Servicio'?['Servicio','Proyecto'].includes(x.source_type):x.source_type===$('#billingType').value)));};
const originalBilling=renderBilling;renderBilling=function(){originalBilling();const rows=db.billing.filter(x=>quarterOf(x.date)===currentQuarter()&&Number((x.date||'').slice(0,4))===currentYear());const sum=a=>a.reduce((s,x)=>s+Number(x.paid_amount??0),0);$('#bQuarterTotal').textContent=money(sum(rows));$('#bAffiliateTotal').textContent=money(sum(rows.filter(x=>x.source_type==='Afiliación')));$('#bServicesTotal').textContent=money(sum(rows.filter(x=>['Servicio','Proyecto'].includes(x.source_type))));$('#bPendingTotal').textContent=money(db.billing.filter(x=>x.status!=='Rechazada').reduce((s,x)=>s+Math.max(0,(x.total??0)-(x.paid_amount??0)),0));};
const originalMoneyModal=moneyModal;moneyModal=function(id=''){originalMoneyModal(id);const x=db.money.find(x=>x.id===id)||{};$('#mcontent .formgrid').insertAdjacentHTML('beforeend',`<div><label>Herramienta vinculada</label><select id="cmTool"><option value="">Sin vincular</option>${db.tools.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div><label>Red (obligatoria si hay transacción externa)</label><input id="cmNetwork" value="${esc(x.network||'')}"></div><div><label>Comisión realmente cobrada €</label><input id="cmPaid" type="number" step=".01" value="${esc(x.paid_commission??'')}"></div><div><label>Fecha de cobro</label><input id="cmDate" type="date" value="${esc(x.paid_date||'')}"></div><div><label>Vencimiento previsto</label><input id="cmDue" type="date" value="${esc(x.due_date||'')}"></div><div><label>Visitor ID (distinto del Click ID)</label><input id="cmVisitor" value="${esc(x.visitor_id||'')}"></div>`);$('#cmTool').value=x.tool_id||'';};
saveMoney=async function(id){const tool=db.tools.find(x=>x.id===$('#cmTool').value);if($('#c7').value&&!$('#cmNetwork').value.trim())throw Error('Indica la red para evitar transacciones duplicadas');await upsert('money',{id:id||uid(),date:$('#c1').value,tool:tool?.name||$('#c2').value,tool_id:tool?.id||null,sale:$('#c3').value===''?null:+$('#c3').value,expected:$('#c4').value===''?null:+$('#c4').value,reported:$('#c5').value===''?null:+$('#c5').value,status:$('#c6').value,partner_id:$('#c7').value||null,click_id:$('#c8').value||null,network:$('#cmNetwork').value||null,paid_commission:$('#cmPaid').value===''?null:+$('#cmPaid').value,paid_date:$('#cmDate').value||null,due_date:$('#cmDue').value||null,visitor_id:$('#cmVisitor').value||null});if(!connected)await syncBillingFromCommission(db.money.find(x=>x.id===id)||db.money.at(-1));closeM();};
const originalToolModal=toolModal;toolModal=function(id=''){originalToolModal(id);if(!id)$('#a4').value='Sin solicitar';const t=db.tools.find(x=>x.id===id)||{};$('#mcontent .formgrid').insertAdjacentHTML('beforeend',`<div class="full"><label>Ficha pública ampliada (datos confirmados, JSON)</label><textarea id="publicData" rows="6">${esc(JSON.stringify(t.public_data||{},null,2))}</textarea><p class="small muted">Usos, público, precio, facilidad, idiomas y funciones. Vacío significa no confirmado. Consulta la plantilla de importación.</p></div>`);};
const originalSaveTool=saveTool;saveTool=async function(id){const data=JSON.parse($('#publicData').value||'{}');if(!data||typeof data!=='object'||Array.isArray(data))throw Error('La ficha debe ser un objeto JSON');const baseUpsert=upsert;upsert=async(t,r)=>baseUpsert(t,t==='tools'?{...r,public_data:data}:r);try{await originalSaveTool(id);}finally{upsert=baseUpsert;}};
globalSearch=function(q){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const box=$('#globalResults');q=String(q).trim().toLocaleLowerCase('es');box.replaceChildren();if(!q){box.classList.remove('open');return;}for(const [t,label] of [['clients','Cliente'],['projects','Proyecto'],['tools','Herramienta / afiliación'],['billing','Factura'],['client_documents','Documento'],['issues','Incidencia'],['leads','Lead']])for(const x of db[t].filter(x=>JSON.stringify(x).toLocaleLowerCase('es').includes(q)).slice(0,5)){const b=document.createElement('button');b.className='global-result';b.textContent=label+' · '+(x.name||x.label||x.party||x.tool||x.type||x.id);b.onclick=()=>{box.classList.remove('open');if(t==='clients')clientModal(x.id);else if(t==='tools')toolModal(x.id);else if(t==='billing')billingModal(x.id);else if(t==='issues')issueModal(x.id);else if(t==='client_documents')openClientDocuments(x.client_id);else entityModal(t,x.id);};box.append(b);}if(!box.children.length)box.textContent='Sin resultados';box.classList.add('open');},180);};
saveClientDocument=async function(clientId){requireAccess();const f=$('#docFile').files[0];if(!f)throw Error('Elige un archivo');if(f.size>25*1024*1024)throw Error('Máximo 25 MB por documento');const id=uid(),path=clientId+'/'+id,meta={id,client_id:clientId,project_id:$('#docProject')?.value||null,label:$('#docLabel').value.trim()||f.name,category:$('#docCategory').value,file_name:f.name,mime_type:f.type||'application/octet-stream',size_bytes:f.size,storage_path:path,uploaded_by:remote.email||'Local'};if(connected){await upsert('client_documents',meta);try{const r=await fetch(`${remote.url}/storage/v1/object/client-documents/${path}`,{method:'POST',headers:{apikey:remote.key,Authorization:'Bearer '+remote.token,'Content-Type':'application/octet-stream'},body:f});if(!r.ok)throw Error('No se pudo subir el archivo');}catch(e){await api(`/rest/v1/client_documents?id=eq.${id}`,{method:'DELETE'});await loadRemote();throw e;}}else{await localFilePut(id,f);await upsert('client_documents',meta);}openClientDocuments(clientId);};
const originalDocs=openClientDocuments;openClientDocuments=function(clientId){originalDocs(clientId);$('#clientDocList').insertAdjacentHTML('beforebegin',`<label>Asociar al proyecto</label><select id="docProject"><option value="">Documentación general del cliente</option>${db.projects.filter(p=>p.client_id===clientId).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select>`);};
deleteClientDocument=async function(id){requireAccess();if(!confirm('¿Eliminar el documento y su archivo?'))return;const d=db.client_documents.find(x=>x.id===id);if(connected){const r=await fetch(remote.url+'/storage/v1/object/client-documents',{method:'DELETE',headers:rh(),body:JSON.stringify({prefixes:[d.storage_path]})});if(!r.ok)throw Error('No se pudo eliminar el archivo. Su ficha se conserva.');await api('/rest/v1/client_documents?id=eq.'+id,{method:'DELETE'});await loadRemote();}else{await localFileDelete(id);db.client_documents=db.client_documents.filter(x=>x.id!==id);save();}openClientDocuments(d.client_id);};
const definitions={projects:[['name','Proyecto'],['client_id','Cliente','clients'],['owner','Responsable','owners'],['status','Estado'],['budget_total','Presupuesto','number'],['invoice_total','Total factura','number'],['invoice_base','Base factura','number'],['vat_percent','IVA %','number'],['invoice_number','Nº factura'],['invoice_date','Fecha factura','date'],['due_date','Vencimiento','date'],['notes','Notas']],payments:[['project_id','Proyecto','projects'],['date','Fecha','date'],['amount','Cobrado €','number'],['reference','Referencia']],leads:[['name','Nombre'],['email','Correo'],['phone','Teléfono'],['source','Origen'],['status','Estado'],['owner','Responsable','owners'],['client_id','Cliente vinculado','clients'],['notes','Notas']]};
function entityModal(t,id=''){requireAccess();const x=db[t].find(x=>x.id===id)||{};openM(t==='projects'?'Proyecto':t==='payments'?'Pago':'Lead',`<div class="formgrid">${definitions[t].map(([key,label,type])=>{let input;if(['clients','projects','owners'].includes(type)){const options=type==='owners'?['Clara','Esther','Clara + Esther'].map(n=>({id:n,name:n})):db[type];input=`<select id="ex_${key}"><option value="">Selecciona</option>${options.map(o=>`<option value="${o.id}" ${x[key]===o.id?'selected':''}>${esc(o.name)}</option>`).join('')}</select>`;}else input=`<input id="ex_${key}" type="${type||'text'}" ${type==='number'?'step=".01" min="0"':''} value="${esc(x[key]??'')}">`;return `<div><label>${label}</label>${input}</div>`;}).join('')}</div><div class="note">Los cobros de proyectos se calculan a partir de sus pagos. Cada proyecto tiene su propia facturación.</div><div class="formactions"><button class="btn" onclick="saveEntity('${t}','${id}')">Guardar</button></div>`);}
async function saveEntity(t,id){let r={id:id||uid()};for(const [key,,type] of definitions[t]){let v=$('#ex_'+key).value;r[key]=type==='number'?(v===''?null:Number(v)):v||null;}if(t!=='payments'&&!r.name)throw Error('Falta nombre');if(t==='projects'&&!r.client_id)throw Error('Selecciona cliente');if(t==='payments'&&(!r.project_id||!r.date||!(r.amount>0)))throw Error('Selecciona proyecto, fecha e importe positivo');if(t==='projects'&&r.budget_total==null)r.budget_total=0;if('owner' in r&&!r.owner)r.owner='Clara + Esther';await upsert(t,r);closeM();}
function renderExtras(){if(!$('#extraRows'))return;const type=$('#extraType').value,filter=($('#extraSearch').value||'').toLowerCase();const rows=db[type].filter(r=>JSON.stringify(r).toLowerCase().includes(filter));$('#extraRows').innerHTML=rows.map(x=>`<tr><td>${esc(x.name||x.reference||x.id)}</td><td>${esc(db.clients.find(c=>c.id===x.client_id)?.name||db.projects.find(p=>p.id===x.project_id)?.name||'')}</td><td>${esc(x.owner||x.date||'')}</td><td>${esc(x.status||x.payment_status||'')}</td><td>${money(x.amount??x.budget_total??0)}</td><td>${money(x.paid_amount??0)}</td><td><button class="mini" onclick="entityModal('${type}','${x.id}')">Editar</button> <button class="mini" onclick="del('${type}','${x.id}')">Eliminar</button></td></tr>`).join('');}
const originalDash=renderDash;renderDash=function(){originalDash();const cutoff=Date.now()-30*86400000,events=db.events.filter(e=>Date.parse(e.created_at)>=cutoff),views=events.filter(e=>e.event_type==='page_view'),clicks=events.filter(e=>e.event_type==='affiliate_click'),sessions=new Set(views.map(e=>e.session_id));const ctr=sessions.size?new Set(clicks.filter(e=>sessions.has(e.session_id)).map(e=>e.session_id)).size/sessions.size*100:0;$('#mPending').textContent=money(db.money.filter(x=>!['Rechazada','Pagada'].includes(x.status)).reduce((s,x)=>s+Math.max(0,(x.reported??x.expected??0)-(x.paid_commission??0)),0));$('#mConv').textContent=db.money.filter(x=>['Aprobada','Pagada'].includes(x.status)).length;
if($('#extraMetrics'))$('#extraMetrics').textContent=`30 días: ${views.length} visitas · ${events.filter(e=>e.event_type==='search').length} búsquedas · CTR por sesión ${ctr.toFixed(1)}% · ${db.leads.length} leads totales · ${db.clients.length} clientes totales. Comisión cobrada: ${money(db.money.reduce((s,x)=>s+(x.paid_commission??0),0))}. Ingresos por servicios: ${money(db.billing.filter(x=>['Proyecto','Servicio'].includes(x.source_type)).reduce((s,x)=>s+(x.paid_amount??0),0))}. Solo actividad con consentimiento; conversiones aportadas por partners.`;
let alerts=[];for(const c of db.money){if(c.reported!=null&&c.expected!=null&&Math.abs(c.reported-c.expected)>.01)alerts.push('Diferencia en comisión: '+c.tool);if(c.due_date&&c.due_date<new Date().toISOString().slice(0,10)&&c.status!=='Pagada'&&c.status!=='Rechazada')alerts.push('Comisión vencida: '+c.tool);if(!c.click_id)alerts.push('Comisión sin evidencia de clic: '+c.tool);}for(const p of db.projects)if(p.due_date&&p.due_date<new Date().toISOString().slice(0,10)&&p.payment_status!=='Pagado')alerts.push('Cobro de proyecto pendiente: '+p.name);for(const t of db.tools)if(t.public_status==='Publicado'&&!t.official_url)alerts.push('Publicada sin URL oficial: '+t.name);$('#alerts').insertAdjacentHTML('beforeend',alerts.map(a=>`<div class="alert">${esc(a)}</div>`).join(''));};
renderPerformance=function(){const rows=db.tools.map(t=>{const e=db.events.filter(x=>x.tool_id===t.id||x.tool_slug===t.tracking_slug),cs=db.money.filter(x=>x.tool_id===t.id);return {name:t.name,views:e.filter(x=>x.event_type==='tool_detail').length,compares:e.filter(x=>x.event_type==='compare_add').length,clicks:e.filter(x=>x.event_type==='affiliate_click').length,conversions:cs.filter(x=>['Aprobada','Pagada'].includes(x.status)).length,paid:cs.reduce((s,x)=>s+(x.paid_commission??0),0)};}).sort((a,b)=>b.paid-a.paid||b.clicks-a.clicks);$('#toolPerformance').innerHTML='<p class="small muted">Acumulado histórico · conversiones vinculadas por ID permanente</p><div class="table"><table><tr><th>Herramienta</th><th>Fichas</th><th>Comparaciones</th><th>Clics</th><th>Conversiones</th><th>Cobrado</th></tr>'+rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.views}</td><td>${x.compares}</td><td>${x.clicks}</td><td>${x.conversions}</td><td>${money(x.paid)}</td></tr>`).join('')+'</table></div>';};
function initV4(){sessionStorage.removeItem('busco_token');sessionStorage.removeItem('busco_email');const style=document.createElement('style');style.textContent='body.locked .side,body.locked .global-search,body.locked .topright button{display:none}body.locked .layout{grid-template-columns:1fr}body.locked main .view:not(#v-settings){display:none!important}button:disabled{opacity:.4;cursor:not-allowed}';document.head.append(style);
$('#billingQuarter').insertAdjacentHTML('afterend','<select id="billingMonth" onchange="renderBilling()"><option value="">Todos los meses</option>'+Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')+'</select><select id="billingType" onchange="renderBilling()"><option value="">Todos los ingresos</option><option>Afiliación</option><option>Servicio</option><option>Otro</option></select>');
$('#v-dash').insertAdjacentHTML('beforeend','<div id="extraMetrics" class="note" style="margin-top:16px"></div>');
$('#v-clients').insertAdjacentHTML('beforeend','<div class="card" style="margin-top:20px"><h2>Proyectos, pagos y leads</h2><div class="toolbar"><select id="extraType" onchange="renderExtras()"><option value="projects">Proyectos</option><option value="payments">Pagos</option><option value="leads">Leads</option></select><input class="field" id="extraSearch" placeholder="Filtrar…" oninput="renderExtras()"><button class="btn" onclick="entityModal(document.getElementById(\'extraType\').value)">Añadir</button></div><div class="table"><table><thead><tr><th>Nombre / referencia</th><th>Cliente / proyecto</th><th>Responsable / fecha</th><th>Estado</th><th>Importe</th><th>Cobrado</th><th></th></tr></thead><tbody id="extraRows"></tbody></table></div></div>');
$('.topright').insertAdjacentHTML('beforeend','<button class="btn" onclick="loadRemote()">Actualizar</button><button class="btn" onclick="logout()">Salir</button>');
$('#v-settings').insertAdjacentHTML('beforeend','<div class="card"><h3>Historial y copia</h3><p>La copia JSON contiene datos; los archivos de Storage se respaldan por separado.</p><button class="btn" onclick="download(\'BUSCO_historial.json\',JSON.stringify(db.audit_log,null,2))">Exportar historial</button></div>');
$('#sbUrl').value=cfg.supabaseUrl||localStorage.getItem('busco_sb_url')||'';$('#sbKey').value=cfg.publishableKey||localStorage.getItem('busco_sb_key')||'';for(const k of Object.keys(tables))db[k]||=[];
if(cfg.allowLocal){load();for(const k of Object.keys(tables))db[k]||=[];$('#mode').textContent='Local · pruebas, no compartido';}else showGate();render();renderExtras();}
initV4();
