/* Pure validation and import planning; also usable by Node tests. */
(function(root){'use strict';
const uuidRE=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const slug=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function safeURL(v){if(!v)return '';const u=new URL(v);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('URL no permitida');return u.href;}
function csv(text){text=String(text).replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0];const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';let rows=[],row=[],cell='',quoted=false;
for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}
if(quoted)throw Error('CSV con comillas sin cerrar');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map(v=>v.trim());if(new Set(headers).size!==headers.length||headers.some(x=>!x))throw Error('Cabeceras vacías o repetidas');return rows.map((r,i)=>{if(r.length!==headers.length)throw Error('Número de columnas incorrecto, fila '+(i+2));return Object.fromEntries(headers.map((h,j)=>[h,r[j].trim()]));});}
const aliases={nombre:'name',herramienta:'name',categoria:'category',descripcion:'description',web:'official_url',url:'official_url',red:'network',estado:'status',enlace_afiliado:'affiliate_url',comision:'commission',recurrente:'recurring',cookie:'cookie_days',atribucion:'attribution',pago:'payout_terms',contacto:'partner_contact',revision:'review_date',notas:'notes',slug:'tracking_slug',conciliacion:'reconciliation_method',metodo_conciliacion:'reconciliation_method'};
const fields=new Set('id name category description official_url public_status network status affiliate_url commission recurring cookie_days attribution payout_terms partner_contact review_date notes tracking_slug reconciliation_method public_data'.split(' '));
function plan(raw,existing,uuid){if(!Array.isArray(raw)||raw.length>1000)throw Error('Se admite una lista de hasta 1.000 herramientas');const changes=[],errors=[],seen=new Set();
raw.forEach((input,n)=>{try{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Fila inválida');let patch={};for(let [k,v] of Object.entries(input)){k=aliases[k]||k;if(!fields.has(k))throw Error('Columna desconocida: '+k);patch[k]=v;}
if(patch.id&&!uuidRE.test(patch.id))throw Error('ID debe ser UUID; usa tracking_slug para tu identificador legible');let byId=existing.find(x=>x.id===patch.id),bySlug=existing.find(x=>x.tracking_slug===patch.tracking_slug&&patch.tracking_slug);if(byId&&bySlug&&byId.id!==bySlug.id)throw Error('ID y slug pertenecen a herramientas distintas');let old=byId||bySlug;if(old&&patch.id&&old.id!==patch.id)throw Error('El slug ya existe con otro ID');if(old&&patch.tracking_slug&&old.tracking_slug!==patch.tracking_slug)throw Error('El slug permanente no se puede cambiar');
if(!old&&!patch.tracking_slug)patch.tracking_slug=slug(patch.name);if(!old&&existing.some(x=>slug(x.name)===slug(patch.name)))throw Error('Nombre existente: indica su ID o slug para actualizar');
let r={...(old||{id:uuid(),public_status:'Borrador',status:'Sin solicitar'}),...patch};if(!String(r.name||'').trim())throw Error('Falta nombre');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.tracking_slug||''))throw Error('Slug inválido');if(seen.has(r.id)||seen.has(r.tracking_slug))throw Error('Herramienta repetida dentro del archivo');
for(const k of ['official_url','affiliate_url'])if(k in r)r[k]=safeURL(r[k]);if(!['Publicado','Borrador','Oculto'].includes(r.public_status))throw Error('Estado público inválido');if(r.public_status==='Publicado'&&!r.official_url)throw Error('Publicar requiere web oficial');
if('recurring' in r){let v=String(r.recurring).toLowerCase();if(!['true','false','si','sí','no','1','0',''].includes(v))throw Error('Recurrente debe ser sí/no');r.recurring=['true','si','sí','1'].includes(v);}
if('cookie_days' in r){r.cookie_days=r.cookie_days===''?null:Number(r.cookie_days);if(r.cookie_days!==null&&(!Number.isInteger(r.cookie_days)||r.cookie_days<0))throw Error('Cookie inválida');}
if('review_date' in r){r.review_date=r.review_date||null;if(r.review_date&&(!/^\d{4}-\d{2}-\d{2}$/.test(r.review_date)||new Date(r.review_date).toISOString().slice(0,10)!==r.review_date))throw Error('Fecha inválida; usa AAAA-MM-DD');}
if(typeof r.public_data==='string')r.public_data=JSON.parse(r.public_data);if(r.public_data&&(typeof r.public_data!=='object'||Array.isArray(r.public_data)))throw Error('public_data debe ser objeto JSON');
seen.add(r.id);seen.add(r.tracking_slug);changes.push({action:old?'update':'create',row:r,before:old||null,expected:old?.updated_at||null});
}catch(e){errors.push({row:n+2,error:e.message});}});return{changes,errors};}
const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replace(/"/g,'""')+'"';
function csvExport(rows){if(!rows.length)return '\uFEFF';const h=[...new Set(rows.flatMap(x=>Object.keys(x)))];return '\uFEFF'+[h.map(cell).join(','),...rows.map(r=>h.map(k=>cell(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\r\n');}
// XLSX: ZIP + XML using browser built-ins. No macros, formulas or external requests.
async function xlsx(file){if(file.size>10*1024*1024)throw Error('XLSX supera 10 MB');const bytes=new Uint8Array(await file.arrayBuffer()),v=new DataView(bytes.buffer);let end=bytes.length-22;while(end>=Math.max(0,bytes.length-65557)&&v.getUint32(end,true)!==0x06054b50)end--;if(end<0)throw Error('ZIP inválido');let p=v.getUint32(end+16,true),count=v.getUint16(end+10,true),files={},total=0;if(count>2000)throw Error('Demasiados archivos');
for(let i=0;i<count;i++){if(v.getUint32(p,true)!==0x02014b50)throw Error('ZIP inválido');const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),rawSize=v.getUint32(p+24,true),nl=v.getUint16(p+28,true),el=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),off=v.getUint32(p+42,true),name=new TextDecoder().decode(bytes.slice(p+46,p+46+nl));p+=46+nl+el+cl;if(!['xl/sharedStrings.xml','xl/worksheets/sheet1.xml'].includes(name))continue;total+=rawSize;if(total>20*1024*1024)throw Error('XLSX descomprimido demasiado grande');const start=off+30+v.getUint16(off+26,true)+v.getUint16(off+28,true);let b=bytes.slice(start,start+size);if(method===8){const reader=new Blob([b]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();let chunks=[],n=0;while(true){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>20*1024*1024){await reader.cancel();throw Error('XLSX demasiado grande');}chunks.push(value);}b=new Uint8Array(await new Blob(chunks).arrayBuffer());}else if(method!==0)throw Error('Compresión no compatible');files[name]=new DOMParser().parseFromString(new TextDecoder().decode(b),'application/xml');}
const sheet=files['xl/worksheets/sheet1.xml'];if(!sheet||sheet.querySelector('parsererror'))throw Error('Falta primera hoja XLSX válida');if(sheet.querySelector('f'))throw Error('Excel contiene fórmulas: pega valores antes de importar');const strings=[...(files['xl/sharedStrings.xml']?.querySelectorAll('si')||[])].map(x=>[...x.querySelectorAll('t')].map(t=>t.textContent).join(''));const rows=[...sheet.querySelectorAll('row')].map(r=>{let a=[];for(const c of r.querySelectorAll('c')){const letters=c.getAttribute('r').match(/^[A-Z]+/)[0];let col=0;for(const s of letters)col=col*26+s.charCodeAt(0)-64;let value=c.querySelector('v')?.textContent||c.querySelector('is')?.textContent||'';a[col-1]=c.getAttribute('t')==='s'?strings[+value]:value;}return a;});if(!rows.length)return[];const h=rows.shift();if(h.some(x=>!x)||new Set(h).size!==h.length)throw Error('Cabeceras inválidas');return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])));}
const api={uuidRE,slug,safeURL,csv,plan,csvExport,xlsx};if(typeof module!=='undefined')module.exports=api;else root.BuscoCore=api;
})(globalThis);
